### PR TITLE
TL/Item name changes

### PR DESCRIPTION
**Pull request by lIllIIlI**
text.hsp
- Personality name changes to fit grammar better

db_item.hsp
- Uppercase item names to proper title format e.g:
  -  "a skull bow" -> "a Skull Bow"
  -  "mani's alarm clock" -> "Mani's Alarm Clock"
- Few translation errors fixed, e.g:
  - "very pistol of mani" -> "Signature Pistol of Mani" (Though you can argue "The Very Pistol of Mani" sounds more imposing)
  - Nyoi-Mimikaki -> Earpick of Desire
  - kemuridama (i did not know what the heck it was for the longest time) -> Smokebomb
  - Sox -> Socks
  - Panty -> Panties (weird english rule, we use plural because it's a garment for both legs...just like we say pants, not pant.

Stuff I didnt change:
shining long hand -> can be Shining Long Needle, (巨大な長針), 針 can translate to both needle and hand, like a clock hand, so I left it.

Still need to change Quality, Ranks, type and food names
image

### CODE REVIEW

**Comment by JianmengYu** [comment]
I really don't know how to say about this, but I think capitalizing the entire ioriginalnameref is very, very questionable to me. Personally, I absolutely do not want my itemnames capitalized (maybe except the unique items). So I was thinking maybe making a function `_ioriginalnameref()` that calls `capitalize` or `uppercase` the words after reading from `ioriginalnameref`, with it's behavior changable with either a tweak or a setting, if people want to, and the Item Highlight function AnnaBanana made could make use of that.

I do agree with the changes to iknownnameref(unidentified item name) though, because Ano often left these either empty or unchanged(after copying from elsewhere). Like `High Potion of Physical` (which I found weird as hell), the original unknown text is just `clear liquid`, but the jp text is `Novelty Medicine` so I changed the en text to that.

About the other translation changes, I know this sounds exceedingly dumb from some Chinese guy with sucky English, sucky Japanese, and sucky Chinese even. Wiki consistency aside, I don't feel like some of the translation to be unnecessary.
- kemuridama, I agree having japanese name is confusing, that's why I'm slowly filling the missing item descriptions in `db_item.hsp`, people will know it's a smokebomb, and the item is (Single-use), `T`hrown instead used as `t`ool.
- Sox, the "singular" socks, while there are another `socks` item in game, I think it might be pun of `Oックス`/`sOx`
- Nyoi means `changes sizes at will`, a reference to `Nyoi-Bo`, kinda weird thinking the image of Goku wielding his Rod of Desires.

Plural cases like panty is handled in `BLOODYSHADE CUSTOM`'s `Proper plural for items`, change that if you want to.

I'm sorry if this makes you feel like having your effort put to waste, I will diff your `item_db` to list the non-capitalize changes you made, and see if fixes like `Heavy Crushing Ball`, `Intertwined Ring` can be applied.

**Comment by JianmengYu** [comment]
Maybe I'm getting too old and used to Ano's bad translations..

**Comment by lIllIIlI** [comment]
Thanks for looking it over, I agree with your points. Since I noticed you were filling out the item descriptions recently I knew some of these changes would be redundant or resolved by the time you finished, so no problem with that.
About the Nyoi case, i dont know. My GPT crossed with DeepL said it meant 'at one's will', but also 'satisfaction' and 'desire', and since I saw on wiki it was just a fluffy earpick, I couldn't see the context referring to Nyoi-bo. Ano lore...

**Comment by JianmengYu** [comment]
Capitalization config option (under Message/Log settings) added in bb818d43fbb9de35d49cd5eb9b8655cfc2a769a0.
Applied some translations.

**Pull request closed without merging**
